"""
PDF Generation service for travel itineraries using ReportLab.
Generates styled, professional multi-page travel schedule documents.
"""

import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


def generate_itinerary_pdf(
    destination: str,
    days: list[dict],
    final_response: str = "",
    flight_info: str = "",
    hotel_info: str = "",
    budget_info: str = "",
) -> bytes:
    """
    Generate a complete, styled PDF travel document.
    Returns bytes of the generated PDF.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    # Custom Clean Typography Styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#111827"),
        spaceAfter=4,
    )

    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#4B5563"),
        spaceAfter=15,
    )

    section_header_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=18,
        textColor=colors.HexColor("#111827"),
        spaceBefore=14,
        spaceAfter=8,
    )

    day_title_style = ParagraphStyle(
        "DayTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#111827"),
    )

    tag_style = ParagraphStyle(
        "TagText",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=colors.HexColor("#059669"),
    )

    body_style = ParagraphStyle(
        "DocBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#374151"),
    )

    footer_style = ParagraphStyle(
        "DocFooter",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#9CA3AF"),
        alignment=TA_CENTER,
    )

    story = []

    # 1. Header Banner
    dest_name = destination.title() if destination else "Your Custom Trip"
    num_days = len(days) if days else "Tailored"
    story.append(Paragraph(f"Full {num_days}-Day Schedule: {dest_name}", title_style))
    story.append(Paragraph(f"Curated AI Travel Plan &bull; Generated by Travel Companion AI", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#E5E7EB"), spaceAfter=14))

    # 2. Day-by-Day Schedule Section
    if days:
        story.append(Paragraph("Day-by-Day Itinerary", section_header_style))
        story.append(Spacer(1, 4))

        for idx, day_info in enumerate(days, start=1):
            day_num = day_info.get("day", idx)
            title = day_info.get("title", f"Day {day_num}")
            tags = " &bull; ".join(day_info.get("tags", ["Sightseeing"]))
            desc = day_info.get("description", "")

            day_header_p = Paragraph(f"<b>Day {day_num}: {title}</b>", day_title_style)
            tag_p = Paragraph(f"Categories: {tags}", tag_style)
            desc_p = Paragraph(desc, body_style)

            card_data = [
                [day_header_p],
                [tag_p],
                [desc_p],
            ]

            card_table = Table(card_data, colWidths=[520])
            card_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E5E7EB")),
                ("LEFTPADDING", (0, 0), (-1, -1), 12),
                ("RIGHTPADDING", (0, 0), (-1, -1), 12),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("ROUNDEDCORNERS", [6, 6, 6, 6]),
            ]))

            story.append(card_table)
            story.append(Spacer(1, 8))

    # 3. Flights & Logistics (if available)
    if flight_info:
        story.append(Spacer(1, 8))
        story.append(Paragraph("Flight & Transport Guidelines", section_header_style))
        clean_flight = flight_info.replace("#", "").replace("*", "")[:700]
        story.append(Paragraph(clean_flight, body_style))

    # 4. Budget & Tips (if available)
    if budget_info:
        story.append(Spacer(1, 8))
        story.append(Paragraph("Budget Assessment & Insights", section_header_style))
        clean_budget = budget_info.replace("#", "").replace("*", "")[:700]
        story.append(Paragraph(clean_budget, body_style))

    # 5. Disclaimer / Footer
    story.append(Spacer(1, 18))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB"), spaceAfter=8))
    story.append(Paragraph("Disclaimer: Pricing and flight availability are estimates generated by AI. Please confirm with official booking providers before travel.", footer_style))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
